In [23]:
import pandas as pd
from google_play_scraper import Sort, reviews_all
import re
from datetime import datetime

In [24]:
# Define bank app IDs
banks = {
    "CBE": "com.combanketh.mobilebanking",
    "BOA": "com.boa.boaMobileBanking",
    "Dashen": "com.dashen.dashensuperapp"
}

In [25]:
# Initialize a list to hold all reviews
all_reviews = []

# Scrape reviews for each bank
for bank_name, app_id in banks.items():
    reviews = reviews_all(app_id, sort=Sort.NEWEST, count=400)
    for review in reviews:
        all_reviews.append({
            'review': review['content'],
            'rating': review['score'],
            'date': review['at'],
            'bank': bank_name,
            'source': 'Google Play Store'
        })

# Convert to DataFrame
df = pd.DataFrame(all_reviews)

In [26]:
df

,review,rating,date,bank,source
0,I cannot send to cbebirr app. through this app.,3,2025-06-05 11:12:49,CBE,Google Play Store
1,good,4,2025-06-05 10:21:59,CBE,Google Play Store
2,not functional,1,2025-06-05 07:38:12,CBE,Google Play Store
3,everytime you uninstall the app you have to re...,1,2025-06-04 21:33:36,CBE,Google Play Store
4,አካውንት የምናስገባበት ቦታ ስም ጽፈን ነው ከዚህ በፊት የላክንባቸውን አ...,4,2025-06-04 20:54:30,CBE,Google Play Store
...,...,...,...,...,...
8987,Best,5,2025-01-13 21:11:58,Dashen,Google Play Store
8988,"Waw Great and innovated,user friendly, always ...",5,2025-01-13 21:01:12,Dashen,Google Play Store
8989,It's Best waww 🙏,5,2025-01-13 09:37:19,Dashen,Google Play Store
8990,Always one step ahead,5,2025-01-13 09:15:03,Dashen,Google Play Store
8991,"Like Me, I Hope It Works Better Than Before.",5,2025-01-11 11:36:49,Dashen,Google Play Store

In [27]:
df.drop_duplicates(subset=['review'], inplace=True)

In [28]:
# Handle missing data
df.dropna(subset=['review', 'rating', 'date'], inplace=True)

In [29]:
df['date'] = pd.to_datetime(df['date'], unit='ms').dt.strftime('%Y-%m-%d')

In [30]:
df.to_csv('bank_reviews.csv', index=False)

In [31]:
df

,review,rating,date,bank,source
0,I cannot send to cbebirr app. through this app.,3,2025-06-05,CBE,Google Play Store
1,good,4,2025-06-05,CBE,Google Play Store
2,not functional,1,2025-06-05,CBE,Google Play Store
3,everytime you uninstall the app you have to re...,1,2025-06-04,CBE,Google Play Store
4,አካውንት የምናስገባበት ቦታ ስም ጽፈን ነው ከዚህ በፊት የላክንባቸውን አ...,4,2025-06-04,CBE,Google Play Store
...,...,...,...,...,...
8986,Faster and userfriendly,5,2025-01-14,Dashen,Google Play Store
8988,"Waw Great and innovated,user friendly, always ...",5,2025-01-13,Dashen,Google Play Store
8989,It's Best waww 🙏,5,2025-01-13,Dashen,Google Play Store
8990,Always one step ahead,5,2025-01-13,Dashen,Google Play Store
8991,"Like Me, I Hope It Works Better Than Before.",5,2025-01-11,Dashen,Google Play Store

In [32]:
print(f"Total reviews collected: {len(df)}")
print(f"Missing data percentage: {df.isnull().mean().max() * 100:.2f}%")

Total reviews collected: 6671
Missing data percentage: 0.00%